I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/act_two_b2.rpy", line 256, in script
    scene evil_castle with shake
  File "game/act_two_b2.rpy", line 256, in <module>
    scene evil_castle with shake
NameError: name 'shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/act_two_b2.rpy", line 256, in script
    scene evil_castle with shake
  File "D:\Renpy\renpy-8.2.0-sdk\renpy\ast.py", line 1359, in execute
    paired = renpy.python.py_eval(self.paired)
  File "D:\Renpy\renpy-8.2.0-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renpy\renpy-8.2.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/act_two_b2.rpy", line 256, in <module>
    scene evil_castle with shake
NameError: name 'shake' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Luvelian 
Mon Mar 11 14:57:55 2024
